SUBSCRIBE_TICKERS = [
    "KXHIGHNY-26MAR13-T52",
    "KXHIGHNY-26MAR13-T45",
    "KXHIGHNY-26MAR13-B51.5",
    "KXHIGHNY-26MAR13-B49.5",
    "KXHIGHNY-26MAR13-B47.5",
    "KXHIGHNY-26MAR13-B45.5",
]
SHM_NAME = "ks_shm_highny"